
package InterfazGrafica;
import javaapplication7.Administrativo;
import javaapplication7.Afiliado;
import javaapplication7.Colecciones;
import javaapplication7.Doctor;

/**
 *
 * @author Fernando
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Colecciones colecciones;
    private Afiliado afiliado;
    private Administrativo administrativo;
    private Doctor doctor;
    
    public MenuPrincipal() {
        initComponents();
       
    }
    
    
    public MenuPrincipal( Afiliado a,Colecciones e) {           //para afiliados
        initComponents();
        
        afiliado=a;
        colecciones=e;
        setTitle("Sistema de Emergencia Medica - Menu Principal"); 
        setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    
    public MenuPrincipal(Administrativo adm, Colecciones e) {   //para administrativos
        initComponents();
        administrativo=adm;
        colecciones=e;
        setTitle("Sistema de Emergencia Medica - Menu Principal");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }  
    
    
    public MenuPrincipal(Doctor d, Colecciones e) {   //para doctores
        initComponents();
        doctor=d;
        colecciones=e;
        setTitle("Sistema de Emergencia Medica - Menu Principal");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }  
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionarAfiliado = new javax.swing.JButton();
        gestionarEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        asistenciaMedica = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gestionarAfiliado.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        gestionarAfiliado.setText("Gestionar Afiliados");
        gestionarAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarAfiliadoActionPerformed(evt);
            }
        });

        gestionarEmpleado.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        gestionarEmpleado.setText("Gestionar Empleados");
        gestionarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarEmpleadoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de Emergencia Medica");

        asistenciaMedica.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        asistenciaMedica.setText("Asistencia Medica");
        asistenciaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistenciaMedicaActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel6)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(asistenciaMedica, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(gestionarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(gestionarAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(gestionarAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(gestionarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(asistenciaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarAfiliadoActionPerformed
        // TODO add your handling code here:
        MenuAfiliado menuaf= new MenuAfiliado(afiliado,colecciones);
        menuaf.setVisible(true);
        dispose();
    }//GEN-LAST:event_gestionarAfiliadoActionPerformed

    private void asistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistenciaMedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistenciaMedicaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void gestionarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarEmpleadoActionPerformed


        MenuEmpleadosPrincipal menuempleados =new MenuEmpleadosPrincipal(administrativo,colecciones);//aca debo enviar todos los empleados
        menuempleados.setVisible(true);
        
        MenuDoctores menuDoctores=MenuDoctores(doctor,colecciones);
        menuDoctores.setVisible(true);
      
        
        this.dispose();
        
        
    }//GEN-LAST:event_gestionarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asistenciaMedica;
    private javax.swing.JButton gestionarAfiliado;
    private javax.swing.JButton gestionarEmpleado;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    private MenuDoctores MenuDoctores(Doctor doctor, Colecciones colecciones) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
